import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { clientConfig } from "@/config/client";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `Privacy policy for ${clientConfig.companyName}. We do not track you, sell your data, or use advertising cookies.`,
  robots: { index: false, follow: false },
  alternates: { canonical: `${clientConfig.siteUrl}/privacy-policy` },
};

const EFFECTIVE_DATE = clientConfig.privacyEffectiveDate;
const COMPANY = clientConfig.companyName;
const EMAIL = clientConfig.email;
const PHONE = clientConfig.phone;
const LOCATION = `${clientConfig.city}, ${clientConfig.state}`;

const sections = [
  {
    title: "1. Overview",
    body: `${COMPANY} is committed to protecting your privacy. This policy explains what information we collect, how we use it, and what we do not do with it. The short version: we do not track you, we do not sell your data, and we do not use advertising cookies.`,
  },
  {
    title: "2. Information We Collect",
    body: `We collect only the information you voluntarily provide when you contact us or request a quote: your name, email address, phone number, and details about your vessel or service needs. We do not collect any information passively beyond basic server logs (IP address, browser type, page visited) that are automatically generated by web servers and retained for a maximum of 30 days.`,
  },
  {
    title: "3. How We Use Your Information",
    body: `Information you submit is used exclusively to respond to your inquiry, schedule and perform services, send appointment confirmations and service updates, and maintain our client records. We do not use your contact information for unsolicited marketing beyond the service context for which you provided it.`,
  },
  {
    title: "4. Cookies and Tracking",
    body: `This website does not use advertising cookies, behavioral tracking pixels, or cross-site tracking technologies. We do not build advertising profiles or share browsing data with ad networks. If we use anonymous analytics tools (such as Vercel Analytics) to understand general site traffic, those tools do not identify you personally and do not set persistent tracking cookies.`,
  },
  {
    title: "5. Data Sharing",
    body: `We do not sell, rent, trade, or share your personal information with third parties for marketing purposes. Your information may be shared only: (a) with service providers who assist in delivering our marine services (such as scheduling or payment processing), under strict confidentiality, or (b) as required by applicable law or legal process.`,
  },
  {
    title: "6. Data Storage and Security",
    body: `Client data is stored securely using industry-standard measures. Access is limited to authorized personnel who need the information to provide services. We retain your information for no longer than 5 years from your last service engagement, after which it is deleted or anonymized.`,
  },
  {
    title: "7. SMS Communications",
    body: `If you provide your phone number and consent to SMS communications via our contact form, you may receive text messages from ${COMPANY} for appointment confirmations and service updates. You may opt out at any time by replying STOP to any message or emailing us at ${EMAIL}. We do not share your phone number with third-party marketing services.`,
  },
  {
    title: "8. Your Rights",
    body: `You may request access to the personal information we hold about you, request correction of inaccurate information, or request deletion of your information at any time by contacting us at ${EMAIL}. We will respond within a reasonable timeframe.`,
  },
  {
    title: "9. Children's Privacy",
    body: `Our website and services are not directed at children under 13. We do not knowingly collect personal information from children. If you believe we have inadvertently collected such information, please contact us immediately.`,
  },
  {
    title: "10. Changes to This Policy",
    body: `We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated effective date. Continued use of our website or services after changes are posted constitutes acceptance of the revised policy.`,
  },
  {
    title: "11. Contact",
    body: `If you have any questions about this Privacy Policy or how we handle your information, please contact us at ${EMAIL} or by phone at ${PHONE}. Our office is based in ${LOCATION}.`,
  },
];

export default function PrivacyPolicyPage() {
  return (
    <>
      <Header />

      <main className="pt-32 pb-24 px-6">
        <div className="max-w-3xl mx-auto">

          {/* Header */}
          <div className="flex flex-col gap-4 mb-12 pb-10 border-b border-steel-dark">
            <p className="text-steel text-[10px] tracking-[0.4em] uppercase">Legal</p>
            <h1 className="text-wake text-3xl sm:text-4xl font-bold tracking-tight">
              Privacy Policy
            </h1>
            <p className="text-steel text-xs leading-relaxed">
              Effective Date: <span className="text-steel-light">{EFFECTIVE_DATE}</span>
              &nbsp;·&nbsp; Company: <span className="text-steel-light">{COMPANY}</span>
              &nbsp;·&nbsp; Location: <span className="text-steel-light">{LOCATION}</span>
            </p>
            <p className="text-steel-light text-sm leading-relaxed">
              We do not track you. We do not sell your data. We collect only what is
              necessary to provide our marine services and communicate with you about
              your vessel.
            </p>
          </div>

          {/* Sections */}
          <div className="flex flex-col gap-10">
            {sections.map((s) => (
              <article key={s.title} className="flex flex-col gap-3">
                <h2 className="text-wake text-sm font-bold tracking-tight">{s.title}</h2>
                <p className="text-steel text-sm leading-relaxed">{s.body}</p>
              </article>
            ))}
          </div>

          {/* Footer nav */}
          <div className="mt-16 pt-10 border-t border-steel-dark flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <p className="text-steel text-xs">
              Questions? Contact us at{" "}
              <a href={`mailto:${EMAIL}`} className="text-navy hover:text-wake transition-colors">
                {EMAIL}
              </a>
            </p>
            <Link
              href="/"
              className="text-steel text-xs tracking-[0.25em] uppercase hover:text-wake transition-colors duration-200"
            >
              ← Back to Home
            </Link>
          </div>

        </div>
      </main>

      <Footer />
    </>
  );
}
